### ISSUE TITLE
check execution 20160207 errors

### ISSUE THREAD

**Issue by hvaldecantos** [hvaldecantos/gvarharmfulness#7]
When executing `data_collector.rb` file, projects gedit, make, and screen raised `No such file or directory`

```
------------------> gedit
Already on 'master'
/home/gvar/gvarharmfulness/gvar/lib/cmd_runner.rb:19:in `block in run': find: `gedit': No such file or directory (StandardError)
        from /home/gvar/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/open3.rb:199:in `popen_run'
        from /home/gvar/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/open3.rb:93:in `popen3'
        from /home/gvar/gvarharmfulness/gvar/lib/cmd_runner.rb:15:in `run'
        from /home/gvar/gvarharmfulness/gvar/lib/cmd.rb:9:in `analyze_result'
        from /home/gvar/gvarharmfulness/gvar/lib/find_dirs_cmd.rb:13:in `run'
        from /home/gvar/gvarharmfulness/gvar/lib/extract_macro_tokens_cmd.rb:14:in `run'
        from /home/gvar/gvarharmfulness/gvar/lib/find_gv_cmd.rb:18:in `run'
        from /home/gvar/gvarharmfulness/gvar/lib/store_commits_cmd.rb:41:in `block in run'
        from /home/gvar/gvarharmfulness/gvar/lib/store_commits_cmd.rb:38:in `each'
        from /home/gvar/gvarharmfulness/gvar/lib/store_commits_cmd.rb:38:in `run'
        from /home/gvar/gvarharmfulness/gvar/lib/g_var_cli.rb:28:in `run'
        from /home/gvar/gvarharmfulness/gvar/bin/gvar:5:in `<top (required)>'
        from /home/gvar/.rvm/gems/ruby-2.2.0@gvarharmfulness/bin/gvar:23:in `load'
        from /home/gvar/.rvm/gems/ruby-2.2.0@gvarharmfulness/bin/gvar:23:in `<main>'
        from /home/gvar/.rvm/gems/ruby-2.2.0@gvarharmfulness/bin/ruby_executable_hooks:15:in `eval'
        from /home/gvar/.rvm/gems/ruby-2.2.0@gvarharmfulness/bin/ruby_executable_hooks:15:in `<main>'
```

```
------------------> make
Already on 'master'
/home/gvar/gvarharmfulness/gvar/lib/cmd_runner.rb:19:in `block in run': ctags: No files specified. Try "ctags --help". (StandardError)
        from /home/gvar/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/open3.rb:199:in `popen_run'
        from /home/gvar/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/open3.rb:93:in `popen3'
        from /home/gvar/gvarharmfulness/gvar/lib/cmd_runner.rb:15:in `run'
        from /home/gvar/gvarharmfulness/gvar/lib/cmd.rb:9:in `analyze_result'
        from /home/gvar/gvarharmfulness/gvar/lib/find_gv_cmd.rb:23:in `run'
        from /home/gvar/gvarharmfulness/gvar/lib/store_commits_cmd.rb:41:in `block in run'
        from /home/gvar/gvarharmfulness/gvar/lib/store_commits_cmd.rb:38:in `each'
        from /home/gvar/gvarharmfulness/gvar/lib/store_commits_cmd.rb:38:in `run'
        from /home/gvar/gvarharmfulness/gvar/lib/g_var_cli.rb:28:in `run'
        from /home/gvar/gvarharmfulness/gvar/bin/gvar:5:in `<top (required)>'
        from /home/gvar/.rvm/gems/ruby-2.2.0@gvarharmfulness/bin/gvar:23:in `load'
        from /home/gvar/.rvm/gems/ruby-2.2.0@gvarharmfulness/bin/gvar:23:in `<main>'
        from /home/gvar/.rvm/gems/ruby-2.2.0@gvarharmfulness/bin/ruby_executable_hooks:15:in `eval'
        from /home/gvar/.rvm/gems/ruby-2.2.0@gvarharmfulness/bin/ruby_executable_hooks:15:in `<main>'
```

```
------------------> screen
Already on 'master'
/home/gvar/gvarharmfulness/gvar/lib/cmd_runner.rb:19:in `block in run': find: `src': No such file or directory (StandardError)
        from /home/gvar/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/open3.rb:199:in `popen_run'
        from /home/gvar/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/open3.rb:93:in `popen3'
        from /home/gvar/gvarharmfulness/gvar/lib/cmd_runner.rb:15:in `run'
        from /home/gvar/gvarharmfulness/gvar/lib/cmd.rb:9:in `analyze_result'
        from /home/gvar/gvarharmfulness/gvar/lib/find_dirs_cmd.rb:13:in `run'
        from /home/gvar/gvarharmfulness/gvar/lib/extract_macro_tokens_cmd.rb:14:in `run'
        from /home/gvar/gvarharmfulness/gvar/lib/find_gv_cmd.rb:18:in `run'
        from /home/gvar/gvarharmfulness/gvar/lib/store_commits_cmd.rb:41:in `block in run'
        from /home/gvar/gvarharmfulness/gvar/lib/store_commits_cmd.rb:38:in `each'
        from /home/gvar/gvarharmfulness/gvar/lib/store_commits_cmd.rb:38:in `run'
        from /home/gvar/gvarharmfulness/gvar/lib/g_var_cli.rb:28:in `run'
        from /home/gvar/gvarharmfulness/gvar/bin/gvar:5:in `<top (required)>'
        from /home/gvar/.rvm/gems/ruby-2.2.0@gvarharmfulness/bin/gvar:23:in `load'
        from /home/gvar/.rvm/gems/ruby-2.2.0@gvarharmfulness/bin/gvar:23:in `<main>'
        from /home/gvar/.rvm/gems/ruby-2.2.0@gvarharmfulness/bin/ruby_executable_hooks:15:in `eval'
```

**Comment by hvaldecantos** [comment]
Gedit project:
The error happens in SHA1 608d7a6b9b7f6d71376814ac7bbb450babe8882a because the directory project is empty, this is the second commit. Furthermore, this commit does not have a commit message, therefore we cannot use it. This error doesn't affect the results. This is the log of execution:

```
I, [2016-02-11T18:49:34.879431 #23268]  INFO -- : git checkout 801d3852a339a5b0ab5583ba91b203fa0bc3a14b
I, [2016-02-11T18:49:34.987104 #23268]  INFO -- : find gedit -type f -name '*.c' -or -name '*.h'
I, [2016-02-11T18:49:34.989607 #23268]  INFO -- : cat gedit/*.c gedit/*.h | grep -i '^ *# *define '
I, [2016-02-11T18:49:34.995074 #23268]  INFO -- : ctags -x --c-kinds=v --file-scope=no --language-force=c -I DUMMY_TOKEN,__GEPREFS_H__,PREFS_FILE,BUFFER_SIZE,STATE_SPACE, ...,__MENUS_H__ gedit/*.c gedit/*.h
I, [2016-02-11T18:49:35.004622 #23268]  INFO -- : git log --reverse --first-parent --unified=0 801d3852a339a5b0ab5583ba91b203fa0bc3a14b^..801d3852a339a5b0ab5583ba91b203fa0b$
I, [2016-02-11T18:49:35.017773 #23268]  INFO -- : git checkout 608d7a6b9b7f6d71376814ac7bbb450babe8882a
I, [2016-02-11T18:49:35.126683 #23268]  INFO -- : find  -type f -name '*.c' -or -name '*.h'
I, [2016-02-11T18:49:35.128887 #23268]  INFO -- : ctags -x --c-kinds=v --file-scope=no --language-force=c -I DUMMY_TOKEN
I, [2016-02-11T18:49:35.400088 #26020]  INFO -- : git checkout master
```

We can see that `ctags` is called with no files as the last parameter, that produces the `No files specified` error.

Make project:
The error was because there was no `.c` or `.h` code to analyse in a commit. Now the script check this case. This error is fixed.

Screen project:
This is similar to gedit project.

**Comment by hvaldecantos** [comment]
Screen project:

```
I, [2016-02-12T23:36:15.385988 #27658]  INFO -- : git checkout 30f597b9f18d355253b9484bb2f4a1fa5e2e3fb8
I, [2016-02-12T23:36:15.403123 #27658]  INFO -- : find  -type f -name '*.c' -or -name '*.h'
I, [2016-02-12T23:36:15.405376 #27658]  INFO -- : ctags -x --c-kinds=v --file-scope=no --language-force=c -I DUMMY_TOKEN
```

**Comment by hvaldecantos** [comment]
fix in https://github.com/hvaldecantos/gvar/commit/5d633819ce4c68a54a42199f3d6c5559766e3e01
